import { Router } from "express";
import { login } from "./login.js";
import { register } from "./register.js";
import { updatePassword } from "../controllers/updatePassword.js";
import { authMiddleware } from "../middleware/authMiddleware.js";
import { forgotPassword } from "../controllers/forgotPassword.js";
const router = Router();
router.post("/login", login);
router.post("/register", register);
router.put("/update-password", authMiddleware, updatePassword);
router.post("/forgot-password", forgotPassword);
export default router;